# SPDX-License-Identifier: MIT
# Copyright (c) 2026 Kesavan Mariappan (kesavan-mariappan-devops)
# https://github.com/kesavan-mariappan-devops/k8s-istio-platform

# Enforces mTLS for all services in backend namespace
apiVersion: security.istio.io/v1beta1
kind: PeerAuthentication
metadata:
  name: backend-mtls
  namespace: backend
spec:
  mtls:
    mode: STRICT
---
# Enforces mTLS for all services in frondend namespace
apiVersion: security.istio.io/v1beta1
kind: PeerAuthentication
metadata:
  name: frontend-mtls
  namespace: frontend
spec:
  mtls:
    mode: STRICT
