# SPDX-License-Identifier: MIT
# Copyright (c) 2026 Kesavan Mariappan (kesavan-mariappan-devops)
# https://github.com/kesavan-mariappan-devops/k8s-istio-platform

apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: mesh-ui-vs
  namespace: frontend
spec:
  hosts:
    - "k8s-istio-platform.frontend.local"
  gateways:
    - istio-system/k8s-istio-platform-gateway
  http:
    - match:
        - uri:
            prefix: /
      route:
        - destination:
            host: mesh-ui.frontend.svc.cluster.local
            port:
              number: 80
